name: Laravel test case

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Step to print contents of .env.testing file for debugging
      - name: Print contents of .env.testing file
        run: cat .env.testing

      # Step to set database variables from .env.testing file
      - name: Set database variables from .env.testing file
        run: |
          echo "Reading .env.testing file..."
          source .env.testing
          export DB_CONNECTION DB_HOST DB_PORT DB_DATABASE DB_USERNAME DB_PASSWORD

      # Step to print database connection details for debugging
      - name: Print database connection details
        run: |
          echo "Database Connection: ${DB_CONNECTION}"
          echo "Database Host: ${DB_HOST}"
          echo "Database Port: ${DB_PORT}"
          echo "Database Name: ${DB_DATABASE}"
          echo "Database Username: ${DB_USERNAME}"
          echo "Database Password: ${DB_PASSWORD}"

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Run database migrations
        run: php artisan migrate --force

      - name: Run Pest tests
        run: ENV=testing ./vendor/bin/pest
