name: Laravel test case

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      DB_HOST: 127.0.0.1
      DB_PORT: 3306
      DB_DATABASE: epsilontile_testing
      DB_USERNAME: root
      DB_PASSWORD: root

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create MySQL configuration file
        run: |
          echo "[client]" > ~/.my.cnf
          echo "user=root" >> ~/.my.cnf
          echo "password=root" >> ~/.my.cnf

      - name: Check if database exists
        id: check_db
        run: |
          if mysql -h"${DB_HOST}" -e "use ${DB_DATABASE}"; then
            echo "Database exists"
            echo "database_exists=true" >> $GITHUB_ENV
          else
            echo "Database does not exist"
            echo "database_exists=false" >> $GITHUB_ENV
          fi

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Create database if it doesn't exist
        if: steps.check_db.outputs.database_exists == 'false'
        run: |
          mysql -h"${DB_HOST}" -e "CREATE DATABASE ${DB_DATABASE}"

      - name: Run database migrations
        run:  php artisan migrate --force --env=testing

      - name: Run Pest tests
        run: ENV=testing ./vendor/bin/pest
