name: Laravel test case

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Read .env.testing file and set database variables
        id: env
        run: |
          echo "Reading .env.testing file..."
          export $(grep -v '^#' .env.testing | xargs -d '\n')

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Run database migrations
        run: php artisan migrate --force

      - name: Run Pest tests
        run: ./vendor/bin/pest
