name: Laravel test case

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${{ secrets.DB_DATABASE }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create .env.testing file
        run: |
          echo "DB_CONNECTION=mysql" > .env.testing
          echo "DB_HOST=localhost" >> .env.testing
          echo "DB_PORT=3306" >> .env.testing
          echo "DB_DATABASE=${{ secrets.DB_DATABASE }}" >> .env.testing
          echo "DB_USERNAME=root" >> .env.testing
          echo "DB_PASSWORD=root" >> .env.testing

      - name: Wait for MySQL to be ready
        run: |
          echo "Waiting for MySQL to be ready..."
          for i in {1..30}; do
            mysqladmin ping --silent && echo "MySQL is up and running" && break
            echo "Waiting..."
            sleep 2
          done

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

       - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Run database migrations
        run: php artisan migrate --force

      - name: Run Pest tests
        run: ./vendor/bin/pest
