name: Laravel test case

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      DB_HOST: 127.0.0.1
      DB_PORT: 3306
      DB_DATABASE: epsilontile_testing
      DB_USERNAME: root
      DB_PASSWORD: root

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Step to check if the database exists and create it if necessary
      - name: Check if database exists
        id: check_db
        run: |
          # Check if the database exists
          if mysql -h localhost -u root -p root -e "use epsilontile_testing"; then
            echo "Database exists"
            echo "database_exists=true" >> $GITHUB_ENV
          else
            echo "Database does not exist"
            echo "database_exists=false" >> $GITHUB_ENV
          fi

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Create database if it doesn't exist
        if: steps.check_db.outputs.database_exists == 'false'
        run: |
          # Create the database
          mysql mysql -h localhost -u root -p root -e "CREATE DATABASE epsilontile_testing"

      - name: Run database migrations
        run: php artisan migrate --force

      - name: Run Pest tests
        run: ENV=testing ./vendor/bin/pest
