name: Laravel test case

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      DB_DATABASE: epsilon
      DB_USER: root
      DB_PASSWORD: wot-epsilon-test-2024

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Start MySQL
        run: |
          sudo /etc/init.d/mysql start
          echo "Waiting for MySQL to be ready..."
          for i in {1..30}; do
            mysqladmin -h 192.168.1.102 -u root --password=wot-epsilon-test-2024 ping --silent && echo "MySQL is up and running" && break
            echo "Waiting..."
            sleep 2
          done
          mysql -h 192.168.1.102 -u root --password=wot-epsilon-test-2024 -e "CREATE DATABASE IF NOT EXISTS epsilon;"

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Copy .env.testing
        run: cp .env.testing .env

      - name: Update DB_HOST
        run: sed -i 's/DB_HOST=127.0.0.1/DB_HOST=192.168.1.102/g' .env

      - name: Run database migrations
        env:
          DB_CONNECTION: mysql
          DB_HOST: 192.168.1.102
          DB_PORT: 3329
          DB_DATABASE: ${{ env.DB_DATABASE }}
          DB_USERNAME: ${{ env.DB_USER }}
          DB_PASSWORD: ${{ env.DB_PASSWORD }}
        run: php artisan migrate --force

      - name: Run Pest tests
        env:
          DB_CONNECTION: mysql
          DB_HOST: 192.168.1.102
          DB_PORT: 3329
          DB_DATABASE: ${{ env.DB_DATABASE }}
          DB_USERNAME: ${{ env.DB_USER }}
          DB_PASSWORD: ${{ env.DB_PASSWORD }}
        run: ./vendor/bin/pest
