name: Mysql Testing Database

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      DB_DATABASE: epsilontile_testing
      DB_USER: root
      DB_PASSWORD: root

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Start MySQL
        run: |
          sudo /etc/init.d/mysql start
          echo "Waiting for MySQL to be ready..."
          for i in {1..30}; do
            mysqladmin ping --silent && echo "MySQL is up and running" && break
            echo "Waiting..."
            sleep 2
          done
          mysql -e "CREATE DATABASE IF NOT EXISTS $DB_DATABASE;" -u$DB_USER -p$DB_PASSWORD

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Run database migrations
        env:
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_DATABASE: ${{ env.DB_DATABASE }}
          DB_USERNAME: ${{ env.DB_USER }}
          DB_PASSWORD: ${{ env.DB_PASSWORD }}
        run: php artisan migrate --force

      - name: Run Pest tests
        env:
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_DATABASE: ${{ env.DB_DATABASE }}
          DB_USERNAME: ${{ env.DB_USER }}
          DB_PASSWORD: ${{ env.DB_PASSWORD }}
        run: ./vendor/bin/pest




name: Unit Tests

on: [pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_DATABASE: epsilon
          MYSQL_ROOT_PASSWORD: wot-epsilon-test-2024
        ports:
          - 3329:3306
        options: --health-cmd="mysqladmin ping --silent" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Wait for MySQL to be ready
        run: |
          echo "Waiting for MySQL to be ready..."
          for i in {1..30}; do
            if mysqladmin ping -h 192.168.1.102 -P 3329 --silent; then
              echo "MySQL is up and running"
              break
            fi
            echo "Waiting..."
            sleep 2
          done

      - name: Debug MySQL Connection
        run: |
          echo "Testing MySQL connection..."
          mysql -h 192.168.1.102 -P 3329 -u root -pwot-epsilon-test-2024 -e "SHOW DATABASES;"

      - name: Run database migrations
        env:
          DB_CONNECTION: mysql
          DB_HOST: 192.168.1.102
          DB_PORT: 3329
          DB_DATABASE: epsilon
          DB_USERNAME: root
          DB_PASSWORD: wot-epsilon-test-2024
        run: php artisan migrate --force

      - name: Run Pest tests
        env:
          DB_CONNECTION: mysql
          DB_HOST: 192.168.1.102
          DB_PORT: 3329
          DB_DATABASE: epsilon
          DB_USERNAME: root
          DB_PASSWORD: wot-epsilon-test-2024
        run: ./vendor/bin/pest
