name: Laravel test case CI/CD

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      DB_CONNECTION: mysql
      DB_HOST: 192.168.1.102
      DB_PORT: 3329
      DB_DATABASE: epsilon
      DB_USERNAME: root
      DB_PASSWORD: wot-epsilon-test-2024

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Start MySQL
        run: |
          sudo /etc/init.d/mysql start
          echo "Waiting for MySQL to be ready..."
          for i in {1..30}; do
            mysqladmin ping --silent && echo "MySQL is up and running" && break
            echo "Waiting..."
            sleep 2
          done

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Run database migrations
        env:
          DB_CONNECTION: mysql
          DB_HOST: 192.168.1.102
          DB_PORT: 3329
          DB_DATABASE: epsilon
          DB_USERNAME: root
          DB_PASSWORD: wot-epsilon-test-2024

      - name: Run database migrations
        run: php artisan migrate --force

      - name: Run Pest tests
        run: ./vendor/bin/pest
