name: Unit Tests

on: [pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_DATABASE: epsilon
          MYSQL_ROOT_PASSWORD: wot-epsilon-test-2024
        ports:
          - 3329:3306
        volumes:
          - mysql:/var/lib/mysql
          - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Run Pest tests
        run: ./vendor/bin/pest
